
package com.hzih.face.recognition.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FARSWebCommon", targetNamespace = "http://criminal.endpoints.business.ivsign.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FARSWebCommon {


    /**
     * 
     * @param information
     * @param license
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FARS_MODIFY_FACE_POINT")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FARS_MODIFY_FACE_POINT", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSMODIFYFACEPOINT")
    @ResponseWrapper(localName = "FARS_MODIFY_FACE_POINTResponse", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSMODIFYFACEPOINTResponse")
    public String farsMODIFYFACEPOINT(
            @WebParam(name = "license", targetNamespace = "")
            String license,
            @WebParam(name = "information", targetNamespace = "")
            String information);

    /**
     * 
     * @param information
     * @param license
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FARS_1TON_RETURN_ALL_INFO")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FARS_1TON_RETURN_ALL_INFO", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARS1TONRETURNALLINFO")
    @ResponseWrapper(localName = "FARS_1TON_RETURN_ALL_INFOResponse", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARS1TONRETURNALLINFOResponse")
    public String fars1TONRETURNALLINFO(
            @WebParam(name = "license", targetNamespace = "")
            String license,
            @WebParam(name = "information", targetNamespace = "")
            String information);

    /**
     * 
     * @param information
     * @param license
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FARS_DELETE_IMAGE")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FARS_DELETE_IMAGE", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSDELETEIMAGE")
    @ResponseWrapper(localName = "FARS_DELETE_IMAGEResponse", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSDELETEIMAGEResponse")
    public String farsDELETEIMAGE(
            @WebParam(name = "license", targetNamespace = "")
            String license,
            @WebParam(name = "information", targetNamespace = "")
            String information);

    /**
     * 
     * @param information
     * @param license
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FARS_1TON")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FARS_1TON", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARS1TON")
    @ResponseWrapper(localName = "FARS_1TONResponse", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARS1TONResponse")
    public String fars1TON(
            @WebParam(name = "license", targetNamespace = "")
            String license,
            @WebParam(name = "information", targetNamespace = "")
            String information);

    /**
     * 
     * @param information
     * @param license
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FARS_GET_LOGICDBINFOS")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FARS_GET_LOGICDBINFOS", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSGETLOGICDBINFOS")
    @ResponseWrapper(localName = "FARS_GET_LOGICDBINFOSResponse", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSGETLOGICDBINFOSResponse")
    public String farsGETLOGICDBINFOS(
            @WebParam(name = "license", targetNamespace = "")
            String license,
            @WebParam(name = "information", targetNamespace = "")
            String information);

    /**
     * 
     * @param information
     * @param license
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FARS_GET_JOB_INFO")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FARS_GET_JOB_INFO", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSGETJOBINFO")
    @ResponseWrapper(localName = "FARS_GET_JOB_INFOResponse", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSGETJOBINFOResponse")
    public String farsGETJOBINFO(
            @WebParam(name = "license", targetNamespace = "")
            String license,
            @WebParam(name = "information", targetNamespace = "")
            String information);

    /**
     * 
     * @param information
     * @param license
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FARS_GET_PERSONINFO")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FARS_GET_PERSONINFO", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSGETPERSONINFO")
    @ResponseWrapper(localName = "FARS_GET_PERSONINFOResponse", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSGETPERSONINFOResponse")
    public String farsGETPERSONINFO(
            @WebParam(name = "license", targetNamespace = "")
            String license,
            @WebParam(name = "information", targetNamespace = "")
            String information);

    /**
     * 
     * @param information
     * @param license
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FARS_DELETE_PERSON")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FARS_DELETE_PERSON", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSDELETEPERSON")
    @ResponseWrapper(localName = "FARS_DELETE_PERSONResponse", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSDELETEPERSONResponse")
    public String farsDELETEPERSON(
            @WebParam(name = "license", targetNamespace = "")
            String license,
            @WebParam(name = "information", targetNamespace = "")
            String information);

    /**
     * 
     * @param information
     * @param license
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FARS_MODIFY_PERSON")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FARS_MODIFY_PERSON", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSMODIFYPERSON")
    @ResponseWrapper(localName = "FARS_MODIFY_PERSONResponse", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSMODIFYPERSONResponse")
    public String farsMODIFYPERSON(
            @WebParam(name = "license", targetNamespace = "")
            String license,
            @WebParam(name = "information", targetNamespace = "")
            String information);

    /**
     * 
     * @param information
     * @param license
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FARS_ADD_PERSON")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FARS_ADD_PERSON", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSADDPERSON")
    @ResponseWrapper(localName = "FARS_ADD_PERSONResponse", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSADDPERSONResponse")
    public String farsADDPERSON(
            @WebParam(name = "license", targetNamespace = "")
            String license,
            @WebParam(name = "information", targetNamespace = "")
            String information);

    /**
     * 
     * @param information
     * @param license
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FARS_ADD_IMAGE")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FARS_ADD_IMAGE", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSADDIMAGE")
    @ResponseWrapper(localName = "FARS_ADD_IMAGEResponse", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSADDIMAGEResponse")
    public String farsADDIMAGE(
            @WebParam(name = "license", targetNamespace = "")
            String license,
            @WebParam(name = "information", targetNamespace = "")
            String information);

    /**
     * 
     * @param information
     * @param license
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FARS_GET_PAGINATION_RESULT")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FARS_GET_PAGINATION_RESULT", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSGETPAGINATIONRESULT")
    @ResponseWrapper(localName = "FARS_GET_PAGINATION_RESULTResponse", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSGETPAGINATIONRESULTResponse")
    public String farsGETPAGINATIONRESULT(
            @WebParam(name = "license", targetNamespace = "")
            String license,
            @WebParam(name = "information", targetNamespace = "")
            String information);

    /**
     * 
     * @param information
     * @param license
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FARS_GET_JOB_IDS")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FARS_GET_JOB_IDS", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSGETJOBIDS")
    @ResponseWrapper(localName = "FARS_GET_JOB_IDSResponse", targetNamespace = "http://criminal.endpoints.business.ivsign.com/", className = "com.hzih.center.client.FARSGETJOBIDSResponse")
    public String farsGETJOBIDS(
            @WebParam(name = "license", targetNamespace = "")
            String license,
            @WebParam(name = "information", targetNamespace = "")
            String information);

}
